package bongari.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import bongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.09.09 16:00:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class BongauksetTest {



  // Generated by ComTest BEGIN
  /** testLisaa21 */
  @Test
  public void testLisaa21() {    // Bongaukset: 21
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    assertEquals("From: Bongaukset line: 24", 0, bongaukset.getLkm()); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 26", 1, bongaukset.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm37 */
  @Test
  public void testGetLkm37() {    // Bongaukset: 37
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setBongausId(1); 
    assertEquals("From: Bongaukset line: 41", 0, bongaukset.getLkm()); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 43", 1, bongaukset.getLkm()); 
    bongaukset.poista(bongaus.getBongausId()); 
    assertEquals("From: Bongaukset line: 45", 0, bongaukset.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista57 */
  @Test
  public void testPoista57() {    // Bongaukset: 57
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setBongausId(1); 
    assertEquals("From: Bongaukset line: 61", 0, bongaukset.getLkm()); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 63", 1, bongaukset.getLkm()); 
    bongaukset.poista(0); 
    assertEquals("From: Bongaukset line: 65", 1, bongaukset.getLkm()); 
    bongaukset.poista(1); 
    assertEquals("From: Bongaukset line: 67", 0, bongaukset.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMuokkaa82 */
  @Test
  public void testMuokkaa82() {    // Bongaukset: 82
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setBongausId(1); 
    bongaus.setJasenId(1); 
    Bongaus muokattava = new Bongaus(); 
    muokattava.setBongausId(1); 
    muokattava.setJasenId(2); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 91", 1, bongaukset.haeJasenenBongaukset(1).size()); 
    bongaukset.muokkaa(muokattava); 
    assertEquals("From: Bongaukset line: 93", 0, bongaukset.haeJasenenBongaukset(1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHaeJasenenBongaukset110 */
  @Test
  public void testHaeJasenenBongaukset110() {    // Bongaukset: 110
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setBongausId(1); 
    bongaus.setJasenId(1); 
    Bongaus bongaus2 = new Bongaus(); 
    bongaus2.setBongausId(2); 
    bongaus2.setJasenId(1); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 119", 1, bongaukset.haeJasenenBongaukset(1).size()); 
    bongaukset.lisaa(bongaus2); 
    assertEquals("From: Bongaukset line: 121", 2, bongaukset.haeJasenenBongaukset(1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHaeBongattavanBongaukset137 */
  @Test
  public void testHaeBongattavanBongaukset137() {    // Bongaukset: 137
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setBongausId(1); 
    bongaus.setBongattavaId(1); 
    Bongaus bongaus2 = new Bongaus(); 
    bongaus2.setBongausId(2); 
    bongaus2.setBongattavaId(1); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 146", 1, bongaukset.haeBongattavanBongaukset(1).size()); 
    bongaukset.lisaa(bongaus2); 
    assertEquals("From: Bongaukset line: 148", 2, bongaukset.haeBongattavanBongaukset(1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaaTietorakenteeseen164 
   * @throws ExceptionHandler when error
   */
  @Test
  public void testLisaaTietorakenteeseen164() throws ExceptionHandler {    // Bongaukset: 164
    List<String> rivit = new ArrayList<String>(); 
    String rivi = "1|1|1|Jyväskylä|01/01/2020|Helppo löytö"; 
    rivit.add(rivi); 
    Bongaukset bongaukset = new Bongaukset(); 
    assertEquals("From: Bongaukset line: 171", 0, bongaukset.getLkm()); 
    bongaukset.lisaaTietorakenteeseen(rivit); 
    assertEquals("From: Bongaukset line: 173", 1, bongaukset.getLkm()); 
  } // Generated by ComTest END
}