package bongari.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import bongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.09.09 16:21:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class BongattavatTest {



  // Generated by ComTest BEGIN
  /** testGetLkm27 */
  @Test
  public void testGetLkm27() {    // Bongattavat: 27
    Bongattavat bongattavat = new Bongattavat(); 
    assertEquals("From: Bongattavat line: 29", 0, bongattavat.getLkm()); 
    Bongattava bongattava = new Bongattava(); 
    bongattavat.lisaa(bongattava); 
    assertEquals("From: Bongattavat line: 32", 1, bongattavat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testBongattava44 */
  @Test
  public void testBongattava44() {    // Bongattavat: 44
    Bongattavat bongattavat = new Bongattavat(); 
    Bongattava bongattava = new Bongattava(); 
    bongattavat.lisaa(bongattava); 
    assertEquals("From: Bongattavat line: 48", 1, bongattavat.getAlkiot().size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa59 */
  @Test
  public void testLisaa59() {    // Bongattavat: 59
    Bongattavat bongattavat = new Bongattavat(); 
    Bongattava bongattava = new Bongattava(); 
    Bongattava bongattava2 = new Bongattava(); 
    bongattavat.lisaa(bongattava); 
    assertEquals("From: Bongattavat line: 64", 1, bongattavat.getLkm()); 
    bongattavat.lisaa(bongattava2); 
    assertEquals("From: Bongattavat line: 66", 2, bongattavat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsi79 */
  @Test
  public void testEtsi79() {    // Bongattavat: 79
    Bongattavat bongattavat = new Bongattavat(); 
    Bongattava bongattava = new Bongattava(); 
    bongattava.setBongattavaId(1); 
    bongattava.setNimi("Kissa"); 
    Bongattava bongattava2 = new Bongattava(); 
    bongattava2.setBongattavaId(2); 
    bongattava2.setNimi("Kassa"); 
    bongattavat.lisaa(bongattava); bongattavat.lisaa(bongattava2); 
    assertEquals("From: Bongattavat line: 88", 2, bongattavat.etsi("ssa").size()); 
    assertEquals("From: Bongattavat line: 89", 1, bongattavat.etsi("kissa").size()); 
    assertEquals("From: Bongattavat line: 90", 1, bongattavat.etsi("IsSa").size()); 
    assertEquals("From: Bongattavat line: 91", 0, bongattavat.etsi("koira").size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna106 */
  @Test
  public void testAnna106() {    // Bongattavat: 106
    Bongattavat bongattavat = new Bongattavat(); 
    Bongattava bongattava = new Bongattava(); 
    bongattava.setBongattavaId(1); 
    bongattavat.lisaa(bongattava); 
    Bongattava loytynyt = bongattavat.anna(1); 
    Bongattava loytynyt2 = bongattavat.anna(0); 
    assertEquals("From: Bongattavat line: 113", 1, loytynyt.getBongattavaId()); 
    assertEquals("From: Bongattavat line: 114", null, loytynyt2); 
  } // Generated by ComTest END
}