package bongari.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import bongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.11.14 18:05:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class BongattavatTest {



  // Generated by ComTest BEGIN
  /** testGetLkm25 */
  @Test
  public void testGetLkm25() {    // Bongattavat: 25
    Bongattavat bongattavat = new Bongattavat(); 
    assertEquals("From: Bongattavat line: 27", 0, bongattavat.getLkm()); 
    Bongattava bongattava = new Bongattava(); 
    bongattavat.lisaa(bongattava); 
    assertEquals("From: Bongattavat line: 30", 1, bongattavat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testBongattava41 */
  @Test
  public void testBongattava41() {    // Bongattavat: 41
    Bongattavat bongattavat = new Bongattavat(); 
    Bongattava bongattava = new Bongattava(); 
    bongattavat.lisaa(bongattava); 
    assertEquals("From: Bongattavat line: 45", 1, bongattavat.getAlkiot().size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa56 */
  @Test
  public void testLisaa56() {    // Bongattavat: 56
    Bongattavat bongattavat = new Bongattavat(); 
    Bongattava bongattava = new Bongattava(); 
    Bongattava bongattava2 = new Bongattava(); 
    bongattavat.lisaa(bongattava); 
    assertEquals("From: Bongattavat line: 61", 1, bongattavat.getLkm()); 
    bongattavat.lisaa(bongattava2); 
    assertEquals("From: Bongattavat line: 63", 2, bongattavat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsi76 */
  @Test
  public void testEtsi76() {    // Bongattavat: 76
    Bongattavat bongattavat = new Bongattavat(); 
    Bongattava bongattava = new Bongattava(); 
    bongattava.setBongattavaId(1); 
    bongattava.setNimi("Kissa"); 
    Bongattava bongattava2 = new Bongattava(); 
    bongattava2.setBongattavaId(2); 
    bongattava2.setNimi("Kassa"); 
    bongattavat.lisaa(bongattava); bongattavat.lisaa(bongattava2); 
    assertEquals("From: Bongattavat line: 85", 2, bongattavat.etsi("ssa").size()); 
    assertEquals("From: Bongattavat line: 86", 1, bongattavat.etsi("kissa").size()); 
    assertEquals("From: Bongattavat line: 87", 1, bongattavat.etsi("IsSa").size()); 
    assertEquals("From: Bongattavat line: 88", 0, bongattavat.etsi("koira").size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna110 */
  @Test
  public void testAnna110() {    // Bongattavat: 110
    Bongattavat bongattavat = new Bongattavat(); 
    Bongattava bongattava = new Bongattava(); 
    bongattava.setBongattavaId(1); 
    bongattavat.lisaa(bongattava); 
    Bongattava loytynyt = bongattavat.anna(1); 
    Bongattava loytynyt2 = bongattavat.anna(0); 
    assertEquals("From: Bongattavat line: 117", 1, loytynyt.getBongattavaId()); 
    assertEquals("From: Bongattavat line: 118", null, loytynyt2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta128 
   * @throws ExceptionHandler when error
   */
  @Test
  public void testLueTiedostosta128() throws ExceptionHandler {    // Bongattavat: 128
    Bongattavat bongattavat = new Bongattavat(); 
    String hakemisto = "data/testikerho/"; 
    try {
    bongattavat.lueTiedostosta(hakemisto + "linnt"); 
    fail("Bongattavat: 134 Did not throw ExceptionHandler");
    } catch(ExceptionHandler _e_){ _e_.getMessage(); }
    bongattavat = new Bongattavat();  // Poistetaan vanhat luomalla uusi
    bongattavat.lueTiedostosta(hakemisto + "linnut");  // johon ladataan tiedot tiedostosta.
    assertEquals("From: Bongattavat line: 137", 257, bongattavat.getAlkiot().size()); 
  } // Generated by ComTest END
}