package bongari.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import bongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.11.02 10:36:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class BongauksetTest {



  // Generated by ComTest BEGIN
  /** testLisaa25 */
  @Test
  public void testLisaa25() {    // Bongaukset: 25
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    assertEquals("From: Bongaukset line: 28", 0, bongaukset.getLkm()); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 30", 1, bongaukset.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm41 */
  @Test
  public void testGetLkm41() {    // Bongaukset: 41
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setBongausId(1); 
    assertEquals("From: Bongaukset line: 45", 0, bongaukset.getLkm()); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 47", 1, bongaukset.getLkm()); 
    bongaukset.poista(bongaus.getBongausId()); 
    assertEquals("From: Bongaukset line: 49", 0, bongaukset.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista62 */
  @Test
  public void testPoista62() {    // Bongaukset: 62
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setBongausId(1); 
    assertEquals("From: Bongaukset line: 66", 0, bongaukset.getLkm()); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 68", 1, bongaukset.getLkm()); 
    bongaukset.poista(0); 
    assertEquals("From: Bongaukset line: 70", 1, bongaukset.getLkm()); 
    bongaukset.poista(1); 
    assertEquals("From: Bongaukset line: 72", 0, bongaukset.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMuokkaa91 */
  @Test
  public void testMuokkaa91() {    // Bongaukset: 91
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setBongausId(1); 
    bongaus.setJasenId(1); 
    Bongaus muokattava = new Bongaus(); 
    muokattava.setBongausId(1); 
    muokattava.setJasenId(2); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 100", 1, bongaukset.haeJasenenBongaukset(1).size()); 
    bongaukset.muokkaa(muokattava); 
    assertEquals("From: Bongaukset line: 102", 0, bongaukset.haeJasenenBongaukset(1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHaeJasenenBongaukset119 */
  @Test
  public void testHaeJasenenBongaukset119() {    // Bongaukset: 119
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setBongausId(1); 
    bongaus.setJasenId(1); 
    Bongaus bongaus2 = new Bongaus(); 
    bongaus2.setBongausId(2); 
    bongaus2.setJasenId(1); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 128", 1, bongaukset.haeJasenenBongaukset(1).size()); 
    bongaukset.lisaa(bongaus2); 
    assertEquals("From: Bongaukset line: 130", 2, bongaukset.haeJasenenBongaukset(1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHaeBongattavanBongaukset146 */
  @Test
  public void testHaeBongattavanBongaukset146() {    // Bongaukset: 146
    Bongaukset bongaukset = new Bongaukset(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setBongausId(1); 
    bongaus.setBongattavaId(1); 
    Bongaus bongaus2 = new Bongaus(); 
    bongaus2.setBongausId(2); 
    bongaus2.setBongattavaId(1); 
    bongaukset.lisaa(bongaus); 
    assertEquals("From: Bongaukset line: 155", 1, bongaukset.haeBongattavanBongaukset(1).size()); 
    bongaukset.lisaa(bongaus2); 
    assertEquals("From: Bongaukset line: 157", 2, bongaukset.haeBongattavanBongaukset(1).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaaTietorakenteeseen173 
   * @throws ExceptionHandler when error
   */
  @Test
  public void testLisaaTietorakenteeseen173() throws ExceptionHandler {    // Bongaukset: 173
    List<String> rivit = new ArrayList<String>(); 
    String rivi = "1|1|1|Jyväskylä|01/01/2020|Helppo löytö"; 
    rivit.add(rivi); 
    Bongaukset bongaukset = new Bongaukset(); 
    assertEquals("From: Bongaukset line: 180", 0, bongaukset.getLkm()); 
    bongaukset.lisaaTietorakenteeseen(rivit); 
    assertEquals("From: Bongaukset line: 182", 1, bongaukset.getLkm()); 
  } // Generated by ComTest END
}