package bongari.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import bongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.09.05 17:32:45 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenetTest {



  // Generated by ComTest BEGIN
  /** testLisaa25 */
  @Test
  public void testLisaa25() {    // Jasenet: 25
    Jasenet jasenet = new Jasenet(); 
    Jasen testi = new Jasen(); 
    jasenet.lisaa(testi); 
    assertEquals("From: Jasenet line: 29", 1, jasenet.getLkm()); 
    Jasen testi2 = new Jasen(); 
    Jasen testi3 = new Jasen(); 
    Jasen testi4 = new Jasen(); 
    Jasen testi5 = new Jasen(); 
    Jasen testi6 = new Jasen(); 
    jasenet.lisaa(testi2); jasenet.lisaa(testi3); jasenet.lisaa(testi4); jasenet.lisaa(testi5); 
    try {
    jasenet.lisaa(testi6); 
    fail("Jasenet: 36 Did not throw Error");
    } catch(Error _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm52 */
  @Test
  public void testGetLkm52() {    // Jasenet: 52
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen = new Jasen(); 
    jasenet.lisaa(jasen); 
    assertEquals("From: Jasenet line: 56", 1, jasenet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna68 */
  @Test
  public void testAnna68() {    // Jasenet: 68
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen1 = new Jasen(); 
    Jasen jasen2 = new Jasen(); 
    jasenet.lisaa(jasen1); jasenet.lisaa(jasen2); 
    assertEquals("From: Jasenet line: 73", jasen1, jasenet.anna(0)); 
    assertEquals("From: Jasenet line: 74", jasen2, jasenet.anna(1)); 
    try {
    jasenet.anna(3); 
    fail("Jasenet: 75 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}