package bongari.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import bongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.11.16 14:53:44 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenetTest {



  // Generated by ComTest BEGIN
  /** testLisaa32 */
  @Test
  public void testLisaa32() {    // Jasenet: 32
    Jasenet jasenet = new Jasenet(); 
    Jasen testi = new Jasen(); 
    jasenet.lisaa(testi); 
    assertEquals("From: Jasenet line: 36", 1, jasenet.getLkm()); 
    Jasen testi2 = new Jasen(); 
    Jasen testi3 = new Jasen(); 
    Jasen testi4 = new Jasen(); 
    Jasen testi5 = new Jasen(); 
    Jasen testi6 = new Jasen(); 
    jasenet.lisaa(testi2); jasenet.lisaa(testi3); jasenet.lisaa(testi4); jasenet.lisaa(testi5); 
    jasenet.lisaa(testi6); 
    assertEquals("From: Jasenet line: 44", 6, jasenet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista61 
   * @throws ExceptionHandler when error
   */
  @Test
  public void testPoista61() throws ExceptionHandler {    // Jasenet: 61
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen = new Jasen(); 
    jasen.parse("1|Roope|Ankka"); 
    jasenet.lisaa(jasen); 
    assertEquals("From: Jasenet line: 67", 1, jasenet.getLkm()); 
    Jasen jasen2 = new Jasen(); 
    jasen2.parse("2|Aku|Ankka"); 
    jasenet.lisaa(jasen2); 
    assertEquals("From: Jasenet line: 71", 2, jasenet.getLkm()); 
    jasenet.poista(1); 
    assertEquals("From: Jasenet line: 73", 1, jasenet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testMuokkaa92 
   * @throws ExceptionHandler when error
   */
  @Test
  public void testMuokkaa92() throws ExceptionHandler {    // Jasenet: 92
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen = new Jasen(); 
    jasen.parse("1|Repe|Sorsa"); 
    jasenet.lisaa(jasen); 
    assertEquals("From: Jasenet line: 98", "Sorsa", jasenet.annaId(1).getSukunimi()); 
    Jasen muokattuJasen = new Jasen(); 
    muokattuJasen.parse("1|Repe|Ankka"); 
    jasenet.muokkaa(muokattuJasen); 
    assertEquals("From: Jasenet line: 102", "Ankka", jasenet.annaId(1).getSukunimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi120 
   * @throws ExceptionHandler when error
   */
  @Test
  public void testEtsi120() throws ExceptionHandler {    // Jasenet: 120
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen = new Jasen(); 
    jasen.parse("1|Aku|Ankka"); 
    Jasen jasen2 = new Jasen(); 
    jasen2.parse("2|Roope|Ankka"); 
    jasenet.lisaa(jasen); jasenet.lisaa(jasen2); 
    List<Jasen> loydetyt = jasenet.etsi("Ankka"); 
    assertEquals("From: Jasenet line: 130", 2, loydetyt.size()); 
    List<Jasen> loydetyt2 = jasenet.etsi("Ank"); 
    assertEquals("From: Jasenet line: 132", 2, loydetyt2.size()); 
    List<Jasen> loydetyt3 = jasenet.etsi("Pekka"); 
    assertEquals("From: Jasenet line: 134", 0, loydetyt3.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiJasenenIndeksi159 
   * @throws ExceptionHandler when error
   */
  @Test
  public void testEtsiJasenenIndeksi159() throws ExceptionHandler {    // Jasenet: 159
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen = new Jasen(); 
    jasen.parse("1|Repe|Sorsa"); 
    Jasen jasen2 = new Jasen(); 
    jasen2.parse("2|Aku|Ankka"); 
    jasenet.lisaa(jasen); jasenet.lisaa(jasen2); 
    int indeksi = jasenet.etsiJasenenIndeksi(1); 
    assertEquals("From: Jasenet line: 168", 0, indeksi); 
    int indeksi2 = jasenet.etsiJasenenIndeksi(2); 
    assertEquals("From: Jasenet line: 170", 1, indeksi2); 
    int indeksiEiLoydy = jasenet.etsiJasenenIndeksi(3); 
    assertEquals("From: Jasenet line: 172", -1, indeksiEiLoydy); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm186 */
  @Test
  public void testGetLkm186() {    // Jasenet: 186
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen = new Jasen(); 
    jasenet.lisaa(jasen); 
    assertEquals("From: Jasenet line: 190", 1, jasenet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna202 */
  @Test
  public void testAnna202() {    // Jasenet: 202
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen1 = new Jasen(); 
    Jasen jasen2 = new Jasen(); 
    jasenet.lisaa(jasen1); jasenet.lisaa(jasen2); 
    assertEquals("From: Jasenet line: 207", jasen1, jasenet.anna(0)); 
    assertEquals("From: Jasenet line: 208", jasen2, jasenet.anna(1)); 
    try {
    jasenet.anna(3); 
    fail("Jasenet: 209 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaId222 
   * @throws ExceptionHandler when error
   */
  @Test
  public void testAnnaId222() throws ExceptionHandler {    // Jasenet: 222
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen = new Jasen(); 
    jasen.parse("1|Roope|Ankka"); 
    Jasen jasen2 = new Jasen(); 
    jasen2.parse("2|Repe|Sorsa"); 
    jasenet.lisaa(jasen); jasenet.lisaa(jasen2); 
    Jasen loydetty = jasenet.annaId(1); 
    assertEquals("From: Jasenet line: 231", "Roope", loydetty.getEtunimi()); 
    Jasen loydetty2 = jasenet.annaId(4); 
    assertEquals("From: Jasenet line: 233", null, loydetty2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta246 
   * @throws ExceptionHandler when error
   */
  @Test
  public void testLueTiedostosta246() throws ExceptionHandler {    // Jasenet: 246
    Jasenet jasenet = new Jasenet(); 
    String hakemisto = "data/testikerho/"; 
    try {
    jasenet.lueTiedostosta(hakemisto + "jasent"); 
    fail("Jasenet: 252 Did not throw ExceptionHandler");
    } catch(ExceptionHandler _e_){ _e_.getMessage(); }
    jasenet = new Jasenet();  // Poistetaan vanhat luomalla uusi
    jasenet.lueTiedostosta(hakemisto + "jasenet");  // johon ladataan tiedot tiedostosta.
    Jasen jasen = jasenet.annaId(1); 
    assertEquals("From: Jasenet line: 256", "Testi", jasen.getEtunimi()); 
    assertEquals("From: Jasenet line: 257", "Testaaja", jasen.getSukunimi()); 
    assertEquals("From: Jasenet line: 258", 1, jasen.getJasenId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaJasenet376 
   * @throws ExceptionHandler when error
   */
  @Test
  public void testAnnaJasenet376() throws ExceptionHandler {    // Jasenet: 376
    Jasenet jasenet = new Jasenet(); 
    Jasen jasen = new Jasen(); 
    jasen.parse("1|Aku|Ankka"); 
    Jasen jasen2 = new Jasen(); 
    jasen2.parse("2|Roope|Ankka"); 
    jasenet.lisaa(jasen); jasenet.lisaa(jasen2); 
    assertEquals("From: Jasenet line: 384", 2, jasenet.annaJasenet().size()); 
  } // Generated by ComTest END
}