package bongari.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import bongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.09.07 09:47:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testGetEtunimi19 */
  @Test
  public void testGetEtunimi19() {    // Jasen: 19
    Jasen testi = new Jasen(); 
    Jasen tyhja = new Jasen(); 
    testi.setEtunimi("Testaaja"); 
    assertEquals("From: Jasen line: 23", "Testaaja", testi.getEtunimi()); 
    assertEquals("From: Jasen line: 24", "", tyhja.getEtunimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetEtunimi34 */
  @Test
  public void testSetEtunimi34() {    // Jasen: 34
    Jasen testi = new Jasen(); 
    testi.setEtunimi("Veijo"); 
    assertEquals("From: Jasen line: 37", "Veijo", testi.getEtunimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetSukunimi47 */
  @Test
  public void testSetSukunimi47() {    // Jasen: 47
    Jasen testi = new Jasen(); 
    testi.setSukunimi("Testaaja"); 
    assertEquals("From: Jasen line: 50", "Testaaja", testi.getSukunimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSukunimi60 */
  @Test
  public void testGetSukunimi60() {    // Jasen: 60
    Jasen testi = new Jasen(); 
    testi.setSukunimi("Testaaja"); 
    assertEquals("From: Jasen line: 63", "Testaaja", testi.getSukunimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKokonimi73 */
  @Test
  public void testGetKokonimi73() {    // Jasen: 73
    Jasen testi = new Jasen(); 
    testi.setEtunimi("Testi"); 
    testi.setSukunimi("Testaaja"); 
    assertEquals("From: Jasen line: 77", "Testi Testaaja", testi.getKokonimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi88 */
  @Test
  public void testRekisteroi88() {    // Jasen: 88
    Jasen testi = new Jasen(); 
    testi.rekisteroi(); 
    Jasen testi2 = new Jasen(); 
    testi2.rekisteroi(); 
    assertEquals("From: Jasen line: 93", 1, testi.getJasenId()); 
    assertEquals("From: Jasen line: 94", 2, testi2.getJasenId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testParse108 
   * @throws ExceptionHandler when error
   */
  @Test
  public void testParse108() throws ExceptionHandler {    // Jasen: 108
    Jasen jasen = new Jasen(); 
    jasen.parse("1|Aku|Ankka"); 
    assertEquals("From: Jasen line: 112", "Aku", jasen.getEtunimi()); 
    assertEquals("From: Jasen line: 113", "Ankka", jasen.getSukunimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetJasenId135 */
  @Test
  public void testSetJasenId135() {    // Jasen: 135
    Jasen jasen = new Jasen(); 
    jasen.setJasenId(3); 
    assertEquals("From: Jasen line: 138", 3, jasen.getJasenId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetJasenId149 */
  @Test
  public void testGetJasenId149() {    // Jasen: 149
    Jasen testi = new Jasen(); 
    testi.setJasenId(1); 
    assertEquals("From: Jasen line: 152", 1, testi.getJasenId()); 
  } // Generated by ComTest END
}