package bongari.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import bongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.11.14 19:08:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KerhoTest {



  // Generated by ComTest BEGIN
  /** testLisaa21 */
  @Test
  public void testLisaa21() {    // Kerho: 21
    Kerho kerho = new Kerho(); 
    Jasen jasen = new Jasen(); 
    jasen.setEtunimi("Aku"); 
    jasen.setSukunimi("Ankka"); 
    kerho.lisaa(jasen); 
    assertEquals("From: Kerho line: 27", 1, kerho.etsiJasenet("Aku").size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa38 */
  @Test
  public void testLisaa38() {    // Kerho: 38
    Kerho kerho = new Kerho(); 
    Jasen jasen = new Jasen(); 
    jasen.setEtunimi("Aku"); 
    jasen.setSukunimi("Ankka"); 
    jasen.setJasenId(1); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setJasenId(1); 
    kerho.lisaa(jasen); 
    kerho.lisaa(bongaus); 
    assertEquals("From: Kerho line: 48", 1, kerho.haeJasenenBongaukset(jasen.getJasenId()).size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHaeJasenenBongattavat138 */
  @Test
  public void testHaeJasenenBongattavat138() {    // Kerho: 138
    Kerho kerho = new Kerho(); 
    Jasen jasen = new Jasen(); 
    jasen.rekisteroi(); 
    Bongattava bongattava = new Bongattava(); 
    bongattava.rekisteroi(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setJasenId(jasen.getJasenId()); 
    bongaus.setBongattavaId(bongattava.getBongattavaId()); 
    kerho.lisaa(bongaus); 
    kerho.lisaa(jasen); 
    List<Bongattava> loytyneet; 
    loytyneet = kerho.haeJasenenBongattavat(jasen.getJasenId()); 
    assertEquals("From: Kerho line: 152", 1, loytyneet.size()); 
    Jasen jasen2 = new Jasen(); 
    jasen2.rekisteroi(); 
    Bongaus bongaus2 = new Bongaus(); 
    bongaus2.setJasenId(jasen.getJasenId()); 
    bongaus2.setBongattavaId(bongattava.getBongattavaId()); 
    kerho.lisaa(bongaus2); 
    List<Bongattava> loytyneet2; 
    loytyneet2 = kerho.haeJasenenBongattavat(jasen2.getJasenId()); 
    assertEquals("From: Kerho line: 161", 0, loytyneet2.size()); 
    assertEquals("From: Kerho line: 162", 1, loytyneet.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHaeJasenenBongaukset180 */
  @Test
  public void testHaeJasenenBongaukset180() {    // Kerho: 180
    Kerho kerho = new Kerho(); 
    Jasen jasen = new Jasen(); 
    jasen.rekisteroi(); 
    Bongattava bongattava = new Bongattava(); 
    bongattava.rekisteroi(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setJasenId(jasen.getJasenId()); 
    bongaus.setBongattavaId(bongattava.getBongattavaId()); 
    kerho.lisaa(bongaus); 
    kerho.lisaa(jasen); 
    List<Bongaus> loytyneet; 
    loytyneet = kerho.haeJasenenBongaukset(jasen.getJasenId()); 
    assertEquals("From: Kerho line: 194", 1, loytyneet.size()); 
    Jasen jasen2 = new Jasen(); 
    jasen2.rekisteroi(); 
    Bongaus bongaus2 = new Bongaus(); 
    bongaus2.setJasenId(jasen.getJasenId()); 
    bongaus2.setBongattavaId(bongattava.getBongattavaId()); 
    kerho.lisaa(bongaus2); 
    List<Bongaus> loytyneet2; 
    loytyneet2 = kerho.haeJasenenBongaukset(jasen2.getJasenId()); 
    assertEquals("From: Kerho line: 203", 0, loytyneet2.size()); 
    assertEquals("From: Kerho line: 204", 1, loytyneet.size()); 
  } // Generated by ComTest END
}