package bongari.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import bongari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.09.05 16:55:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KerhoTest {



  // Generated by ComTest BEGIN
  /** testHaeJasenenBongaukset55 */
  @Test
  public void testHaeJasenenBongaukset55() {    // Kerho: 55
    Kerho kerho = new Kerho(); 
    Jasen jasen = new Jasen(); 
    jasen.rekisteroi(); 
    Bongattava bongattava = new Bongattava(); 
    bongattava.rekisteroi(); 
    Bongaus bongaus = new Bongaus(); 
    bongaus.setJasenId(jasen.getJasenId()); 
    bongaus.setBongattavaId(bongattava.getBongattavaId()); 
    kerho.lisaa(bongaus); 
    kerho.lisaa(jasen); 
    List<Bongattava> loytyneet; 
    loytyneet = kerho.haeJasenenBongaukset(jasen.getJasenId()); 
    assertEquals("From: Kerho line: 69", 1, loytyneet.size()); 
  } // Generated by ComTest END
}